version: 2

common: &common
  environment:
    SYMFONY_DEPRECATIONS_HELPER: disabled
    APP_ENV: test
  steps:
    - checkout
    - run: composer install --no-scripts
    - run: php ./vendor/bin/phpunit


jobs:
  test80:
    docker:
      - image: cimg/php:8.0
    <<: *common
  test81:
    docker:
      - image: cimg/php:8.1
    <<: *common
workflows:
    version: 2
    build:
        jobs:
            - test80
            - test81
